# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "938c43be3b1c89a0352190d6712e1278"
application_url = "https://gentle-namely-hostel-forming.trycloudflare.com"
embedded = true
name = "clone-table-of-content"
handle = "clone-table-of-content"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gentle-namely-hostel-forming.trycloudflare.com/auth/callback",
  "https://gentle-namely-hostel-forming.trycloudflare.com/auth/shopify/callback",
  "https://gentle-namely-hostel-forming.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
